In [41]:
import pandas as pd

df=pd.DataFrame({
    "Name":["Aman","Saurav","Karan","Shubham","Abhishek",None,"Sameer"],
    "Age":[22,23,None,22,25,24,26],
    "Marks":[85,None,88,90,56,72,None],
    "Subject":["Math","Physics","Math","Chemistry","Math","Physics","Chemistrty"]
    
})
df

       Name   Age  Marks     Subject
0      Aman  22.0   85.0        Math
1    Saurav  23.0    NaN     Physics
2     Karan   NaN   88.0        Math
3   Shubham  22.0   90.0   Chemistry
4  Abhishek  25.0   56.0        Math
5       NaN  24.0   72.0     Physics
6    Sameer  26.0    NaN  Chemistrty

In [42]:
df.shape

(7, 4)

In [43]:
df.dtypes

Name           str
Age        float64
Marks      float64
Subject        str
dtype: object

In [44]:
print(df.min)
print(df.mean)

<bound method DataFrame.min of        Name   Age  Marks     Subject
0      Aman  22.0   85.0        Math
1    Saurav  23.0    NaN     Physics
2     Karan   NaN   88.0        Math
3   Shubham  22.0   90.0   Chemistry
4  Abhishek  25.0   56.0        Math
5       NaN  24.0   72.0     Physics
6    Sameer  26.0    NaN  Chemistrty>
<bound method DataFrame.mean of        Name   Age  Marks     Subject
0      Aman  22.0   85.0        Math
1    Saurav  23.0    NaN     Physics
2     Karan   NaN   88.0        Math
3   Shubham  22.0   90.0   Chemistry
4  Abhishek  25.0   56.0        Math
5       NaN  24.0   72.0     Physics
6    Sameer  26.0    NaN  Chemistrty>

#### Exercise 2

In [45]:
df[["Name","Marks"]]

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5       NaN   72.0
6    Sameer    NaN

In [46]:
df[df["Marks"]>80]

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry

In [47]:
df[(df["Age"]>22.0)&(df["Marks"]>80.0)]

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

#### Exercise 3

In [48]:
df.sort_values("Marks")

       Name   Age  Marks     Subject
4  Abhishek  25.0   56.0        Math
5       NaN  24.0   72.0     Physics
0      Aman  22.0   85.0        Math
2     Karan   NaN   88.0        Math
3   Shubham  22.0   90.0   Chemistry
1    Saurav  23.0    NaN     Physics
6    Sameer  26.0    NaN  Chemistrty

In [52]:
first_highest = df["Marks"].nlargest(1).iloc[-1]
second_highest = df["Marks"].nlargest(2).iloc[-1]
lowest=df["Marks"].nsmallest(1).iloc[-1]
print(first_highest)
print(second_highest)
print(lowest)

90.0
88.0
56.0

#### Missing values

In [ ]:
df.isnull().sum()

Name       1
Age        1
Marks      2
Subject    0
dtype: int64

In [54]:
missing_marks = df[df["Marks"].isnull()]
print(missing_marks)

     Name   Age  Marks     Subject
1  Saurav  23.0    NaN     Physics
6  Sameer  26.0    NaN  Chemistrty

In [55]:
clean_df = df.dropna()
print(clean_df)

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math

In [57]:
print("Original shape:", df.shape)
print("Clean shape:", clean_df.shape)
print("Rows removed:", df.shape[0] - clean_df.shape[0])

Original shape: (7, 4)
Clean shape: (3, 4)
Rows removed: 4